import * as fs from "fs";
import * as path from "path";
import * as pulumi from "@pulumi/pulumi";
import * as fastly from "@pulumi/fastly";

// All secrets come from the environment, never from committed Pulumi config:
// a gitignored .env locally, GitHub Actions secrets in CI. The Fastly API token
// is read by the provider from FASTLY_API_KEY. The Backblaze B2 origin
// credentials are read here and injected into the AWS-v4 signing snippet below.
function requireSecretEnv(name: string): pulumi.Output<string> {
  const value = process.env[name];
  if (!value) {
    throw new Error(
      `Missing required environment variable ${name}. Set it in infra/.env locally or as a GitHub Actions secret in CI.`
    );
  }
  return pulumi.secret(value);
}

const b2AccessKey = requireSecretEnv("B2_APPLICATION_KEY_ID");
const b2SecretKey = requireSecretEnv("B2_APPLICATION_KEY");

// Custom VCL snippets live in ./snippets as plain .vcl files so the source is
// readable and exactly matches what runs at the edge. The B2 auth snippet
// carries placeholder tokens that are replaced with the env secrets here.
const snippetsDir = path.join(__dirname, "snippets");
const appendIndexHtml = fs.readFileSync(
  path.join(snippetsDir, "append-index-html.vcl"),
  "utf8"
);
const b2AuthTemplate = fs.readFileSync(
  path.join(snippetsDir, "b2-private-auth.vcl"),
  "utf8"
);
const b2AuthContent = pulumi
  .all([b2AccessKey, b2SecretKey])
  .apply(([accessKey, secretKey]) =>
    b2AuthTemplate
      .replace("__B2_ACCESS_KEY__", accessKey)
      .replace("__B2_SECRET_KEY__", secretKey)
  );

const site = new fastly.ServiceVcl(
  "site",
  {
    name: "www.tollmanz.com",
    comment: "",
    domains: [{ name: "tollmanz.com" }, { name: "www.tollmanz.com" }],
    backends: [
      {
        name: "backblaze",
        address: "www-tollmanz-com.s3.us-east-005.backblazeb2.com",
        port: 443,
        useSsl: true,
        shield: "iad-va-us",
        sslCertHostname: "www-tollmanz-com.s3.us-east-005.backblazeb2.com",
        sslSniHostname: "www-tollmanz-com.s3.us-east-005.backblazeb2.com",
        sslClientCert: pulumi.secret(""),
        sslClientKey: pulumi.secret(""),
      },
    ],
    gzips: [
      {
        name: "Generated by default compression policy",
        contentTypes: [
          "text/html",
          "application/x-javascript",
          "text/css",
          "application/javascript",
          "text/javascript",
          "application/json",
          "application/vnd.ms-fontobject",
          "application/x-font-opentype",
          "application/x-font-truetype",
          "application/x-font-ttf",
          "application/xml",
          "font/eot",
          "font/opentype",
          "font/otf",
          "image/svg+xml",
          "image/vnd.microsoft.icon",
          "text/plain",
          "text/xml",
        ],
        extensions: [
          "css",
          "js",
          "html",
          "eot",
          "ico",
          "otf",
          "ttf",
          "json",
          "svg",
        ],
      },
    ],
    headers: [
      {
        name: "Generated by force TLS and enable HSTS",
        action: "set",
        type: "response",
        destination: "http.Strict-Transport-Security",
        source: '"max-age=31557600"',
      },
    ],
    requestSettings: [
      {
        name: "Generated by force TLS and enable HSTS",
        forceSsl: true,
      },
    ],
    http3: true,
    snippets: [
      {
        name: "Append index.html",
        type: "recv",
        priority: 150,
        content: appendIndexHtml,
      },
      {
        name: "B2 Private Auth",
        type: "miss",
        content: b2AuthContent,
      },
    ],
  },
  {
    protect: true,
  }
);

export const serviceId = site.id;
export const activeVersion = site.activeVersion;
