baseURL = "https://www.tollmanz.com/"
languageCode = "en-us"
title = "tollmanz.com"
theme = "tollmanz"
description = "tollmanz's personal website"
github_username = "tollmanz"
twitter_username = "tollmanz"
pygmentsUseClasses = true
pygmentsCodeFences = true
[permalinks]
  posts = "/:slug/" # Falls back to :title
  pages = "/:slug/" # Falls back to :title
