import * as fs from "fs";
import * as path from "path";
import * as pulumi from "@pulumi/pulumi";
import * as fastly from "@pulumi/fastly";

// The site is served by GitHub Pages and fronted by Fastly. GitHub Pages is
// multi-tenant and routes purely by the HTTP Host header, so the backend's
// connection identity is deliberately decoupled from its routing identity:
//   - address / SNI / cert hostname = tollmanz.github.io (the github.io origin,
//     whose TLS cert is valid for *.github.io)
//   - overrideHost = www.tollmanz.com (the custom domain configured on the repo,
//     which selects this repo's site and avoids the github.io -> custom-domain
//     301 redirect)
// The custom domain must be set in the repo's Settings > Pages to match
// overrideHost. The Fastly API token is read by the provider from FASTLY_API_KEY;
// no secrets are committed. GitHub Pages is public, so no origin signing is
// needed.

// Custom VCL lives in ./snippets as plain .vcl files so the source is readable
// and exactly matches what runs at the edge. The apex-to-www redirect is split
// across a recv snippet (detects the apex Host and raises a sentinel error) and
// an error snippet (synthesizes the 301).
const snippetsDir = path.join(__dirname, "snippets");
const apexRedirectRecv = fs.readFileSync(
  path.join(snippetsDir, "apex-to-www-recv.vcl"),
  "utf8"
);
const apexRedirectError = fs.readFileSync(
  path.join(snippetsDir, "apex-to-www-error.vcl"),
  "utf8"
);
const cacheControlFetch = fs.readFileSync(
  path.join(snippetsDir, "cache-control-fetch.vcl"),
  "utf8"
);
const forceIdentityFetch = fs.readFileSync(
  path.join(snippetsDir, "force-identity-fetch.vcl"),
  "utf8"
);

// Browser RUM telemetry is proxied to Honeycomb at the edge. The Honeycomb
// ingest key is created and owned by the Honeycomb Pulumi project; read it as a
// secret output here so there is a single source of truth and no manual copy
// step. Bring up the Honeycomb stack before this one (see infra/README.md). The
// proxy snippet carries a placeholder that is replaced with the key here, so the
// key reaches Fastly and Pulumi Cloud state (encrypted) but never the browser.
const honeycombStack = new pulumi.StackReference(
  "tollmanz-gmail-com/tollmanz-com-honeycomb/prod"
);
const honeycombIngestKey = honeycombStack.getOutput("ingestKey");
const honeycombProxyTemplate = fs.readFileSync(
  path.join(snippetsDir, "honeycomb-proxy.vcl"),
  "utf8"
);
const honeycombProxyContent = honeycombIngestKey.apply(key =>
  honeycombProxyTemplate.replace("__HONEYCOMB_INGEST_KEY__", key as string)
);

const site = new fastly.ServiceVcl(
  "site",
  {
    name: "www.tollmanz.com",
    comment: "",
    domains: [{ name: "tollmanz.com" }, { name: "www.tollmanz.com" }],
    backends: [
      {
        name: "github-pages",
        address: "tollmanz.github.io",
        port: 443,
        useSsl: true,
        shield: "iad-va-us",
        overrideHost: "www.tollmanz.com",
        sslCertHostname: "tollmanz.github.io",
        sslSniHostname: "tollmanz.github.io",
      },
      {
        // Backend for the browser RUM proxy. The "Honeycomb RUM proxy" snippet
        // selects this backend for POST /v1/traces. overrideHost forces the
        // Host header so TLS and routing reach Honeycomb's OTLP endpoint.
        name: "honeycomb",
        address: "api.honeycomb.io",
        port: 443,
        useSsl: true,
        overrideHost: "api.honeycomb.io",
        sslCertHostname: "api.honeycomb.io",
        sslSniHostname: "api.honeycomb.io",
      },
    ],
    gzips: [
      {
        name: "Generated by default compression policy",
        contentTypes: [
          "text/html",
          "application/x-javascript",
          "text/css",
          "application/javascript",
          "text/javascript",
          "application/json",
          "application/vnd.ms-fontobject",
          "application/x-font-opentype",
          "application/x-font-truetype",
          "application/x-font-ttf",
          "application/xml",
          "font/eot",
          "font/opentype",
          "font/otf",
          "image/svg+xml",
          "image/vnd.microsoft.icon",
          "text/plain",
          "text/xml",
        ],
        extensions: [
          "css",
          "js",
          "html",
          "eot",
          "ico",
          "otf",
          "ttf",
          "json",
          "svg",
        ],
      },
    ],
    // Enable Fastly's Brotli Compression product. The gzips block above defines
    // which content types are compressed; with Brotli enabled, Fastly serves
    // brotli to capable clients and gzip to the rest, compressing at the edge.
    // Paired with the force-identity-fetch snippet below so the origin returns
    // uncompressed content for Fastly to compress: GitHub Pages never emits
    // brotli, and Fastly only compresses content it receives uncompressed.
    // Requires the account to be entitled to the Brotli product; if the apply
    // fails on enablement, request it from Fastly support.
    productEnablement: {
      brotliCompression: true,
    },
    headers: [
      {
        name: "Generated by force TLS and enable HSTS",
        action: "set",
        type: "response",
        destination: "http.Strict-Transport-Security",
        source: '"max-age=31557600"',
      },
    ],
    requestSettings: [
      {
        name: "Generated by force TLS and enable HSTS",
        forceSsl: true,
      },
    ],
    http3: true,
    snippets: [
      {
        // Priority below the apex redirect (100) so /v1/traces is proxied before
        // any host-based redirect, and its return(pass) keeps the request off the
        // GitHub Pages origin and out of cache.
        name: "Honeycomb RUM proxy",
        type: "recv",
        priority: 90,
        content: honeycombProxyContent,
      },
      {
        name: "Apex to www redirect",
        type: "recv",
        priority: 100,
        content: apexRedirectRecv,
      },
      {
        name: "Apex to www redirect response",
        type: "error",
        content: apexRedirectError,
      },
      {
        name: "Cache-Control by asset class",
        type: "fetch",
        priority: 100,
        content: cacheControlFetch,
      },
      {
        name: "Force identity fetch for edge compression - miss",
        type: "miss",
        priority: 100,
        content: forceIdentityFetch,
      },
      {
        name: "Force identity fetch for edge compression - pass",
        type: "pass",
        priority: 100,
        content: forceIdentityFetch,
      },
    ],
  },
  {
    protect: true,
  }
);

export const serviceId = site.id;
export const activeVersion = site.activeVersion;
